### ISSUE TITLE
🐞Operation namespace not specified

### ISSUE THREAD

**Issue by adam-sandor** [ContainerSolutions/java-operator-sdk#58]
While running the ConcurrencyIT test I get this exception. Looks like the operation on EventDispatcher.java:85 doesn't set the namespace. However it's not so easy to set it, because replacing
`resourceOperation.lockResourceVersion(resource.getMetadata().getResourceVersion()).replace(resource);`
with something like 
`resourceOperation.inNamespace(reource.getMetadata().getNamespace().lockResourceVersion(resource.getMetadata().getResourceVersion()).replace(resource);`
is not possible.

```
[ERROR] Processing event CustomResourceEvent{action=ADDED, resource=[ name=test-custom-resource-4, kind=CustomService, apiVersion=sample.javaoperatorsdk/v1 ,resourceVersion=5180, markedForDeletion: false ], retriesIndex=0} failed.
io.fabric8.kubernetes.client.KubernetesClientException: Namespace mismatch. Item namespace:java-operator-sdk-int-test. Operation namespace:myproject.
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.checkNamespace(OperationSupport.java:181)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleReplace(OperationSupport.java:278)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleReplace(OperationSupport.java:259)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleReplace(BaseOperation.java:824)
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.lambda$replace$1(HasMetadataOperation.java:99)
	at io.fabric8.kubernetes.client.CustomResourceDoneable.done(CustomResourceDoneable.java:34)
	at io.fabric8.kubernetes.client.CustomResourceDoneable.done(CustomResourceDoneable.java:23)
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.replace(HasMetadataOperation.java:105)
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.replace(HasMetadataOperation.java:36)
	at com.github.containersolutions.operator.processing.EventDispatcher.replace(EventDispatcher.java:85)
	at com.github.containersolutions.operator.processing.EventDispatcher.handleEvent(EventDispatcher.java:58)
	at com.github.containersolutions.operator.processing.EventConsumer.processEvent(EventConsumer.java:40)
	at com.github.containersolutions.operator.processing.EventConsumer.run(EventConsumer.java:26)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
```

**Comment by csviri** [comment]
why are we are not getting this anyway else? How do you create the clien?

**Comment by csviri** [comment]
fixed here: https://github.com/ContainerSolutions/java-operator-sdk/pull/62
